config/routes.rb
Rails.application.routes.draw do
  get 'weather/form'

  post 'weather/display'

  root 'weather#form'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def form
  end

  def display
  	if params[:city] != nil
    params[:city].gsub! " ", "_"
end


	  
response = HTTParty.get("http://api.wunderground.com/api/#{ENV['wunderground_key']}/geolookup/conditions/q/#{params['state']}/#{params['city']}.xml")

if response['response']['error'] != nil
    flash[:notice] =  "This city doesn't exist.  Check your spelling and try again!"
    redirect_to action: :form
else
  	@res = {
        city: response['response']['location']['city'],
        state: response['response']['location']['state'],
        country: response['response']['location']['country'],
        updated: response['response']['current_observation']['observation_time'],
        weather: response['response']['current_observation']['weather'],
        weather_icon: response['response']['current_observation']['icon_url'],
        temp: response['response']['current_observation']['temp_f'],
        wind: response['response']['current_observation']['wind_string'],
        more_link: response['response']['current_observation']['forecast_url']
    }
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sunwatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'sunglasses' %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>

</head>
<body>
	<div class="container">
	  <div class="page-header">
        <h1>Sunwatch <small>An application for those who love to watch the weather.</small></h1> 
      </div>
	</div>

<%= yield %>

</body>
</html>

app/views/weather/display.html.erb
<div class="container">
	<div class="col-sm-12">
    	<div class="jumbotron">
	        <h2><%= @res[:city] %>, <%= @res[:state] %> - <%= @res[:country] %></h2>
	        <h3><%= @res[:updated] %></h3>
	        <hr/>
	        <h3>
	            <img src="<%= @res[:weather_icon] %>" alt="<%= @res[:weather] %>"/>
	            <%= @res[:weather] %>
	        </h3>
	        <hr/>
	        <p class="lead">
	            <strong>Temp:</strong> <%= @res[:temp] %>
	        </p>
	        <p class="lead">
	            <strong>Wind:</strong> <%= @res[:wind] %>
	        </p>
			<p>
	            <a href="<%= @res[:more_link] %>" class="btn btn-info">More Forecasts</a>
	            <a href="/" class="btn btn-default">Back Home</a>
	        </p>
		</div>
	</div>
</div>

app/views/weather/form.html.erb
<div class="container">
  <div class="row">
	<div class="col-sm-12">
	  <!--Stuff goes here!-->
	  <% if notice %>
	 	 <div class ="alert alert-message">
	  		<p><%=notice %></p>
	  	</div>
	  <% end %>
	  <%= form_tag weather_display_url do %>
	    <div class="row">
		<div class="col-sm-8">
			<%= label_tag "city", "City", class: "control-label" %>
		    <%= text_field_tag :city, nil, placeholder: "Enter a City", class: "form-control" %>
		</div>
		<div class="col-sm-4">
		    <%= label_tag "state", "State", class: "control-label" %>
		    <%= text_field_tag :state, nil, placeholder: "Enter a State, e.g.: LA", class: "form-control" %>
		</div>
	    </div>
	    <hr/>
	    <%= submit_tag "Submit!", class: "btn btn-default" %>
	<% end %>
	</div>
  </div>
</div>